version: '3.8'

services:
  localstack:
    container_name: localstack-pro
    image: localstack/localstack-pro:latest
    ports:
      - "4666:4566"            # LocalStack Gateway
      - "4610-4659:4510-4559"  # external services port range
    environment:
      - DEBUG=1
      - ACTIVATE_PRO=${ACTIVATE_PRO:-0}
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localstack-network
      
  terraform:
    container_name: terraform-cli
    build:
      context: .
      dockerfile: Dockerfile.terraform
    depends_on:
      - localstack
    environment:
      - USE_LOCALSTACK=true
      - LOCALSTACK_HOST=localstack
      - LOCALSTACK_PORT=4566
      - TF_LOG=${TF_LOG:-INFO}
    volumes:
      - "./terraform:/terraform"
    networks:
      - localstack-network

networks:
  localstack-network:
    driver: bridge
